config/routes.rb
Rails.application.routes.draw do
  root 'builds#index'
  resources :builds
  resources :pipelines
  resources :organizations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/build.rb
class Build < ApplicationRecord
  belongs_to :pipeline
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :pipelines
end

app/models/pipeline.rb
class Pipeline < ApplicationRecord
  belongs_to :organization
  has_many :builds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_action :set_build, only: [:show, :edit, :update, :destroy]

  # GET /builds
  # GET /builds.json
  def index
    @builds = Build.all
  end

  # GET /builds/1
  # GET /builds/1.json
  def show
  end

  # GET /builds/1/edit
  def edit
  end

  # POST /builds
  # POST /builds.json
  def create
    @build = Build.new(build_params)

    respond_to do |format|
      if @build.save
        format.html { redirect_to @build, notice: 'Build was successfully created.' }
        format.json { render :show, status: :created, location: @build }
      else
        format.html { render :new }
        format.json { render json: @build.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /builds/1
  # PATCH/PUT /builds/1.json
  def update
    respond_to do |format|
      if @build.update(build_params)
        format.html { redirect_to @build, notice: 'Build was successfully updated.' }
        format.json { render :show, status: :ok, location: @build }
      else
        format.html { render :edit }
        format.json { render json: @build.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /builds/1
  # DELETE /builds/1.json
  def destroy
    @build.destroy
    respond_to do |format|
      format.html { redirect_to builds_url, notice: 'Build was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_build
      @build = Build.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def build_params
      params.require(:build).permit(:uuid, :message, :branch, :state, :created_at, :scheduled_at, :started_at, :finished_at)
    end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name)
    end
end

app/controllers/pipelines_controller.rb
class PipelinesController < ApplicationController
  before_action :set_pipeline, only: [:show, :edit, :update, :destroy]

  # GET /pipelines
  # GET /pipelines.json
  def index
    @pipelines = Pipeline.all
  end

  # GET /pipelines/1
  # GET /pipelines/1.json
  def show
  end

  # GET /pipelines/1/edit
  def edit
  end

  # POST /pipelines
  # POST /pipelines.json
  def create
    @pipeline = Pipeline.new(pipeline_params)

    respond_to do |format|
      if @pipeline.save
        format.html { redirect_to @pipeline, notice: 'Pipeline was successfully created.' }
        format.json { render :show, status: :created, location: @pipeline }
      else
        format.html { render :new }
        format.json { render json: @pipeline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pipelines/1
  # PATCH/PUT /pipelines/1.json
  def update
    respond_to do |format|
      if @pipeline.update(pipeline_params)
        format.html { redirect_to @pipeline, notice: 'Pipeline was successfully updated.' }
        format.json { render :show, status: :ok, location: @pipeline }
      else
        format.html { render :edit }
        format.json { render json: @pipeline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pipelines/1
  # DELETE /pipelines/1.json
  def destroy
    @pipeline.destroy
    respond_to do |format|
      format.html { redirect_to pipelines_url, notice: 'Pipeline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pipeline
      @pipeline = Pipeline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pipeline_params
      params.require(:pipeline).permit(:name, :slug)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/pipelines_helper.rb
module PipelinesHelper
end

app/views/builds/_form.html.erb
<%= form_with(model: build, local: true) do |form| %>
  <% if build.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(build.errors.count, "error") %> prohibited this build from being saved:</h2>

      <ul>
      <% build.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :uuid %>
    <%= form.text_field :uuid, id: :build_uuid %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message, id: :build_message %>
  </div>

  <div class="field">
    <%= form.label :branch %>
    <%= form.text_field :branch, id: :build_branch %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :build_state %>
  </div>

  <div class="field">
    <%= form.label :created_at %>
    <%= form.datetime_select :created_at, id: :build_created_at %>
  </div>

  <div class="field">
    <%= form.label :scheduled_at %>
    <%= form.datetime_select :scheduled_at, id: :build_scheduled_at %>
  </div>

  <div class="field">
    <%= form.label :started_at %>
    <%= form.datetime_select :started_at, id: :build_started_at %>
  </div>

  <div class="field">
    <%= form.label :finished_at %>
    <%= form.datetime_select :finished_at, id: :build_finished_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/builds/edit.html.erb
<h1>Editing Build</h1>

<%= render 'form', build: @build %>

<%= link_to 'Show', @build %> |
<%= link_to 'Back', builds_path %>

app/views/builds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Builds</h1>

<table>
  <thead>
    <tr>
      <th>Uuid</th>
      <th>Message</th>
      <th>Branch</th>
      <th>State</th>
      <th>Created at</th>
      <th>Scheduled at</th>
      <th>Started at</th>
      <th>Finished at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @builds.each do |build| %>
      <tr>
        <td><%= build.uuid %></td>
        <td><%= build.message %></td>
        <td><%= build.branch %></td>
        <td><%= build.state %></td>
        <td><%= build.created_at %></td>
        <td><%= build.scheduled_at %></td>
        <td><%= build.started_at %></td>
        <td><%= build.finished_at %></td>
        <td><%= link_to 'Show', build %></td>
        <td><%= link_to 'Edit', edit_build_path(build) %></td>
        <td><%= link_to 'Destroy', build, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/builds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uuid:</strong>
  <%= @build.uuid %>
</p>

<p>
  <strong>Message:</strong>
  <%= @build.message %>
</p>

<p>
  <strong>Branch:</strong>
  <%= @build.branch %>
</p>

<p>
  <strong>State:</strong>
  <%= @build.state %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @build.created_at %>
</p>

<p>
  <strong>Scheduled at:</strong>
  <%= @build.scheduled_at %>
</p>

<p>
  <strong>Started at:</strong>
  <%= @build.started_at %>
</p>

<p>
  <strong>Finished at:</strong>
  <%= @build.finished_at %>
</p>

<%= link_to 'Edit', edit_build_path(@build) %> |
<%= link_to 'Back', builds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forge</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre.min.css" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/organizations/_form.html.erb
<%= form_with(model: organization, local: true) do |form| %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :organization_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organizations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>

app/views/pipelines/_form.html.erb
<%= form_with(model: pipeline, local: true) do |form| %>
  <% if pipeline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pipeline.errors.count, "error") %> prohibited this pipeline from being saved:</h2>

      <ul>
      <% pipeline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :pipeline_name %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug, id: :pipeline_slug %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pipelines/edit.html.erb
<h1>Editing Pipeline</h1>

<%= render 'form', pipeline: @pipeline %>

<%= link_to 'Show', @pipeline %> |
<%= link_to 'Back', pipelines_path %>

app/views/pipelines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pipelines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pipelines.each do |pipeline| %>
      <tr>
        <td><%= pipeline.name %></td>
        <td><%= pipeline.slug %></td>
        <td><%= link_to 'Show', pipeline %></td>
        <td><%= link_to 'Edit', edit_pipeline_path(pipeline) %></td>
        <td><%= link_to 'Destroy', pipeline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pipelines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pipeline.name %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @pipeline.slug %>
</p>

<%= link_to 'Edit', edit_pipeline_path(@pipeline) %> |
<%= link_to 'Back', pipelines_path %>